### ISSUE TITLE
Unfinished cleanup in chapter 8 python script?

### ISSUE THREAD

**Issue by ricardoV94** [Freenove/Freenove_Ultimate_Starter_Kit_for_Raspberry_Pi#19]
https://github.com/Freenove/Freenove_Ultimate_Starter_Kit_for_Raspberry_Pi/blob/3b7e9f4d8ba674fc1e758ee745856cd4a29c6304/Code/Python_Code/08.1.1_Softlight/Softlight.py#L40

The destroy method seems to be missing these two function calls (compared to previous chapters):

```python
p.stop()
GPIO.cleanup()
```

Or is there a reason why these are not needed in this example?

**Comment by SuhaylZhao** [comment]
Hi,

Yes, you are right!

Cleanup should be added to the destroy function to clear the configuration of GPIO so that GPIO can be restored to the default state. 

Cleanup is a very powerful function, so the p.stop method is no longer needed. If your other programs are using GPIO, cleanup will affect them.

Thanks.
